language: scala
scala:
  - 2.11.7
addons:
  apt:
    packages: libgmp-dev
install:
  - mkdir lib && cd secp256k1
  - ./autogen.sh
  - ./configure --enable-jni --enable-experimental --enable-module-ecdh
  - sudo make install
  - export LD_LIBRARY_PATH="/usr/local/lib"
  - cd ../
script: "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
