language: scala
scala:
  - 2.11.7
addons:
  apt:
    packages: libgmp-dev
install:
  - mkdir lib && cd secp256k1
  - ./autogen.sh
  - ./configure --enable-jni --enable-experimental --enable-module-ecdh
  - sudo make install
  - cd ../
script: sbt -Djava.library.path=secp256k1/.libs clean coverage test
after_success: "sbt coverageReport coveralls"
